//! `sic run <FILE.sic>`: compile, verify, then run.
//!
//! Verification is not optional here. Running bytecode this process just
//! produced may look redundant, but treating "the VM only ever runs verified
//! bytecode" as an invariant with no exceptions is what makes it worth
//! anything.

use std::process::ExitCode;

use sic_broker::Broker;
use sic_bytecode::Program;
use sic_core::{Digest, SourceFile};
use sic_journal::Journal;
use sic_vm::{DEFAULT_FUEL, FailInfo, Value, Vm};

use super::drive::{Outcome, drive, manifest};
use super::journal::{FileSink, new_run_id};
use super::{EXIT_FAILURE, EXIT_SUSPENDED, compile_source};

pub struct RunOptions<'a> {
    pub journal: Option<&'a str>,
    /// Where to write the run's state if it has to stop and wait.
    pub checkpoint: Option<&'a str>,
}

pub fn run(path: &str, options: RunOptions<'_>) -> ExitCode {
    let (file, program) = match compile_source(path) {
        Ok(v) => v,
        Err(code) => return code,
    };

    let result = sic_verify::verify(&program);
    for w in &result.warnings {
        eprintln!("warning: {w}");
    }
    if !result.ok() {
        // The bytecode came from this process, so a failure here is a compiler
        // bug rather than something the user wrote.
        eprintln!("internal error: the generated bytecode did not verify");
        for e in &result.errors {
            eprintln!("  {e}");
        }
        return ExitCode::from(EXIT_FAILURE);
    }

    let Some(entry) = program.func_by_name("main") else {
        eprintln!("error: `{path}` has no `main` function");
        return ExitCode::from(EXIT_FAILURE);
    };
    if !program.funcs[entry as usize].params.is_empty() {
        eprintln!("error: `main` must take no arguments");
        return ExitCode::from(EXIT_FAILURE);
    }

    let run_id = new_run_id();
    let journal = match options.journal {
        Some(path) => match FileSink::create(path) {
            Ok(sink) => {
                eprintln!("run {run_id} -> {path}");
                Journal::new(run_id, Box::new(sink))
            }
            Err(msg) => {
                eprintln!("error: {msg}");
                return ExitCode::from(EXIT_FAILURE);
            }
        },
        None => Journal::new(run_id, Box::new(sic_journal::NullSink)),
    };

    let mut vm = Vm::with_journal(&program, DEFAULT_FUEL, journal);
    let mut broker = Broker::new(manifest(&program));
    let status = vm.run(entry, &[]);
    let outcome = drive(&mut vm, &mut broker, status);
    finish(&mut vm, &program, &file, outcome, options.checkpoint)
}

/// Reports how a run ended, writing a checkpoint if it stopped to wait.
pub fn finish(
    vm: &mut Vm,
    program: &Program,
    file: &SourceFile,
    outcome: Outcome,
    checkpoint_path: Option<&str>,
) -> ExitCode {
    match outcome {
        Outcome::Finished(Value::Unit) => ExitCode::SUCCESS,
        Outcome::Finished(value) => {
            println!("{}", vm.display(&value));
            ExitCode::SUCCESS
        }
        Outcome::Failed(info) => {
            report_failure(vm, program, file, &info);
            ExitCode::from(EXIT_FAILURE)
        }
        Outcome::Suspended { question } => {
            let Some(path) = checkpoint_path else {
                // Without somewhere to put the state, the only alternative
                // would be to lose the run.
                eprintln!("error: the run is waiting for `{question}` and has nowhere to be saved");
                eprintln!("       pass --checkpoint PATH to write its state out");
                return ExitCode::from(EXIT_FAILURE);
            };
            write_checkpoint(vm, program, path, &question)
        }
    }
}

fn write_checkpoint(vm: &mut Vm, program: &Program, path: &str, question: &str) -> ExitCode {
    // The digest ties the checkpoint to this exact bytecode, so it cannot be
    // resumed against a program that has changed underneath it.
    let digest = Digest::of(&sic_bytecode::encode(program));
    let Some(bytes) = vm.checkpoint(digest, question) else {
        eprintln!("internal error: the run is waiting but has no state to save");
        return ExitCode::from(EXIT_FAILURE);
    };
    if let Err(e) = std::fs::write(path, &bytes) {
        eprintln!("error: cannot write `{path}`: {e}");
        return ExitCode::from(EXIT_FAILURE);
    }
    eprintln!("waiting: {question}");
    eprintln!("saved {} bytes to {path}", bytes.len());
    eprintln!("resume with: sic resume {path} <FILE.sic> --value <VALUE>");
    ExitCode::from(EXIT_SUSPENDED)
}

/// Reports a runtime failure, naming the source line through the debug section.
pub fn report_failure(vm: &Vm, program: &Program, file: &SourceFile, info: &FailInfo) {
    eprint!("error: {}", info.kind.message());
    if let Some(value) = &info.value {
        eprint!(": {}", vm.display(value));
    }
    if let Some(detail) = &info.detail {
        eprint!(": {detail}");
    }
    eprintln!();

    match program.debug.position(info.pc) {
        Some((line, col)) => eprintln!(" --> {}:{}:{}", file.name(), line, col),
        None => eprintln!(" --> in `{}` at instruction {}", info.func, info.pc),
    }
}
