//! `sic run <FILE.sic>`: compile, verify, then run.
//!
//! Verification is not optional here. Running bytecode this process just
//! produced may look redundant, but treating "the VM only ever runs verified
//! bytecode" as an invariant with no exceptions is what makes it worth
//! anything.

use std::process::ExitCode;

use sic_broker::Broker;
use sic_bytecode::Program;
use sic_core::{Digest, SourceFile};
use sic_journal::Journal;
use sic_vm::{DEFAULT_FUEL, FailInfo, Value, Vm};

use super::drive::{Outcome, drive_recording, manifest};
use super::journal::{FileSink, new_run_id};
use super::store;
use super::{EXIT_FAILURE, EXIT_SUSPENDED, compile_source};

pub struct RunOptions<'a> {
    pub journal: Option<&'a str>,
    /// Where to write the run's state if it has to stop and wait.
    pub checkpoint: Option<&'a str>,
    /// Keep the whole run - bytecode, journal, and what the broker answered -
    /// so it can be explained and replayed later.
    pub record: bool,
}

pub fn run(path: &str, options: RunOptions<'_>) -> ExitCode {
    let (file, program) = match compile_source(path) {
        Ok(v) => v,
        Err(code) => return code,
    };

    let result = sic_verify::verify(&program);
    for w in &result.warnings {
        eprintln!("warning: {w}");
    }
    if !result.ok() {
        // The bytecode came from this process, so a failure here is a compiler
        // bug rather than something the user wrote.
        eprintln!("internal error: the generated bytecode did not verify");
        for e in &result.errors {
            eprintln!("  {e}");
        }
        return ExitCode::from(EXIT_FAILURE);
    }

    let Some(entry) = program.func_by_name("main") else {
        eprintln!("error: `{path}` has no `main` function");
        return ExitCode::from(EXIT_FAILURE);
    };
    if !program.funcs[entry as usize].params.is_empty() {
        eprintln!("error: `main` must take no arguments");
        return ExitCode::from(EXIT_FAILURE);
    }

    let run_id = new_run_id();

    // A recorded run keeps the bytecode beside its journal: replaying needs the
    // exact program, and "the file on disk now" is not it.
    let recording = if options.record {
        match store::create(run_id) {
            Ok(dir) => {
                let bytes = sic_bytecode::encode(&program);
                if let Err(e) = std::fs::write(dir.join(store::PROGRAM), &bytes) {
                    eprintln!("error: cannot write the recorded program: {e}");
                    return ExitCode::from(EXIT_FAILURE);
                }
                eprintln!("run {run_id}  recorded in {}", dir.display());
                Some(dir)
            }
            Err(msg) => {
                eprintln!("error: {msg}");
                return ExitCode::from(EXIT_FAILURE);
            }
        }
    } else {
        None
    };

    let journal_path = match (&recording, options.journal) {
        (Some(dir), None) => Some(dir.join(store::JOURNAL).to_string_lossy().into_owned()),
        (_, given) => given.map(str::to_string),
    };
    let journal = match journal_path.as_deref() {
        Some(path) => match FileSink::create(path) {
            Ok(sink) => {
                if recording.is_none() {
                    eprintln!("run {run_id} -> {path}");
                }
                Journal::new(run_id, Box::new(sink))
            }
            Err(msg) => {
                eprintln!("error: {msg}");
                return ExitCode::from(EXIT_FAILURE);
            }
        },
        None => Journal::new(run_id, Box::new(sic_journal::NullSink)),
    };

    let mut vm = Vm::with_journal(&program, DEFAULT_FUEL, journal);
    let mut broker = Broker::new(manifest(&program));
    let status = vm.run(entry, &[]);
    let outcome = drive_recording(&mut vm, &mut broker, status, recording.as_deref());

    // A recorded run that has to wait keeps its checkpoint too, so `sic resume`
    // can find it beside everything else.
    let checkpoint = match (&recording, options.checkpoint) {
        (Some(dir), None) => Some(dir.join(store::CHECKPOINT).to_string_lossy().into_owned()),
        (_, given) => given.map(str::to_string),
    };
    // A recorded run is identified by its id, so that is what the hint uses:
    // nothing about a path has to be remembered.
    let hint = recording
        .as_ref()
        .map(|_| format!("sic attach {} --value <VALUE>", &run_id.to_string()[..8]));
    finish(
        &mut vm,
        &program,
        &file,
        outcome,
        checkpoint.as_deref(),
        hint.as_deref(),
    )
}

/// Reports how a run ended, writing a checkpoint if it stopped to wait.
pub fn finish(
    vm: &mut Vm,
    program: &Program,
    file: &SourceFile,
    outcome: Outcome,
    checkpoint_path: Option<&str>,
    resume_hint: Option<&str>,
) -> ExitCode {
    match outcome {
        Outcome::Finished(Value::Unit) => ExitCode::SUCCESS,
        Outcome::Finished(value) => {
            println!("{}", vm.display(&value));
            ExitCode::SUCCESS
        }
        Outcome::Failed(info) => {
            report_failure(vm, program, file, &info);
            ExitCode::from(EXIT_FAILURE)
        }
        Outcome::Suspended { question } => {
            let Some(path) = checkpoint_path else {
                // Without somewhere to put the state, the only alternative
                // would be to lose the run.
                eprintln!("error: the run is waiting for `{question}` and has nowhere to be saved");
                eprintln!("       pass --checkpoint PATH to write its state out");
                return ExitCode::from(EXIT_FAILURE);
            };
            write_checkpoint(vm, program, path, &question, resume_hint)
        }
    }
}

fn write_checkpoint(
    vm: &mut Vm,
    program: &Program,
    path: &str,
    question: &str,
    resume_hint: Option<&str>,
) -> ExitCode {
    // The digest ties the checkpoint to this exact bytecode, so it cannot be
    // resumed against a program that has changed underneath it.
    let digest = Digest::of(&sic_bytecode::encode(program));
    let Some(bytes) = vm.checkpoint(digest, question) else {
        eprintln!("internal error: the run is waiting but has no state to save");
        return ExitCode::from(EXIT_FAILURE);
    };
    if let Err(e) = std::fs::write(path, &bytes) {
        eprintln!("error: cannot write `{path}`: {e}");
        return ExitCode::from(EXIT_FAILURE);
    }
    eprintln!("waiting: {question}");
    eprintln!("saved {} bytes to {path}", bytes.len());
    match resume_hint {
        Some(hint) => eprintln!("answer with:  {hint}"),
        None => eprintln!("resume with: sic resume {path} <FILE.sic> --value <VALUE>"),
    }
    ExitCode::from(EXIT_SUSPENDED)
}

/// Reports a runtime failure, naming the source line through the debug section.
pub fn report_failure(vm: &Vm, program: &Program, file: &SourceFile, info: &FailInfo) {
    eprint!("error: {}", info.kind.message());
    if let Some(value) = &info.value {
        eprint!(": {}", vm.display(value));
    }
    if let Some(detail) = &info.detail {
        eprint!(": {detail}");
    }
    eprintln!();

    match program.debug.position(info.pc) {
        Some((line, col)) => eprintln!(" --> {}:{}:{}", file.name(), line, col),
        None => eprintln!(" --> in `{}` at instruction {}", info.func, info.pc),
    }
}
