//! `sic run <FILE.sic>`: compile, verify, then run.
//!
//! Verification is not optional here. Running bytecode this process just
//! produced may look redundant, but treating "the VM only ever runs verified
//! bytecode" as an invariant with no exceptions is what makes it worth
//! anything.

use std::process::ExitCode;

use sic_bytecode::Program;
use sic_core::SourceFile;
use sic_vm::{DEFAULT_FUEL, FailInfo, Status, Value, Vm};

use super::{EXIT_FAILURE, compile_source};

pub fn run(path: &str) -> ExitCode {
    let (file, program) = match compile_source(path) {
        Ok(v) => v,
        Err(code) => return code,
    };

    let result = sic_verify::verify(&program);
    for w in &result.warnings {
        eprintln!("warning: {w}");
    }
    if !result.ok() {
        // The bytecode came from this process, so a failure here is a compiler
        // bug rather than something the user wrote.
        eprintln!("internal error: the generated bytecode did not verify");
        for e in &result.errors {
            eprintln!("  {e}");
        }
        return ExitCode::from(EXIT_FAILURE);
    }

    let Some(entry) = program.func_by_name("main") else {
        eprintln!("error: `{path}` has no `main` function");
        return ExitCode::from(EXIT_FAILURE);
    };
    if !program.funcs[entry as usize].params.is_empty() {
        eprintln!("error: `main` must take no arguments");
        return ExitCode::from(EXIT_FAILURE);
    }

    let mut vm = Vm::new(&program, DEFAULT_FUEL);
    match vm.run(entry, &[]) {
        Status::Finished(Value::Unit) => ExitCode::SUCCESS,
        Status::Finished(value) => {
            println!("{}", vm.display(&value));
            ExitCode::SUCCESS
        }
        Status::Failed(info) => {
            report_failure(&vm, &program, &file, &info);
            ExitCode::from(EXIT_FAILURE)
        }
        Status::Suspended(reason) => {
            // Phase 5 turns this into a checkpoint; until then nothing can
            // suspend a run.
            eprintln!("internal error: the run suspended unexpectedly: {reason:?}");
            ExitCode::from(EXIT_FAILURE)
        }
    }
}

/// Reports a runtime failure, naming the source line through the debug section.
fn report_failure(vm: &Vm, program: &Program, file: &SourceFile, info: &FailInfo) {
    eprint!("error: {}", info.kind.message());
    if let Some(value) = &info.value {
        eprint!(": {}", vm.display(value));
    }
    eprintln!();

    match program.debug.position(info.pc) {
        Some((line, col)) => eprintln!(" --> {}:{}:{}", file.name(), line, col),
        None => eprintln!(" --> in `{}` at instruction {}", info.func, info.pc),
    }
}
