[package]
name = "sic-vm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sic-core = { path = "../sic-core" }
sic-bytecode = { path = "../sic-bytecode" }
sic-journal = { path = "../sic-journal" }
sic-json = { path = "../sic-json" }
[lints]
workspace = true
