[package]
name = "sic-ir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sic-core = { path = "../sic-core" }
sic-types = { path = "../sic-types" }
sic-syntax = { path = "../sic-syntax" }
[lints]
workspace = true
